version: '3'

services:
  fastapi_backend:
    privileged: true
    container_name: fastapi-backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code/src
    restart: always

  
  react_frontend:
    container_name: react_frontend
    build: ./react-frontend
    volumes:
      - './react-frontend:/app'
    ports:
      - 3000:3000